#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_upgrade: true
packages:
  - tmux
  - python3
  - python3-pip
runcmd:
  - curl -sSL https://get.docker.com/ | CHANNEL=stable sh
  - pip3 install docker-compose
power_state:
  delay: "+10"
  mode: reboot
  message: Bye Bye
  timeout: 30
